In [142]:
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')

%cd gdrive/MyDrive/ITMO_HW/

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
[Errno 2] No such file or directory: 'gdrive/MyDrive/ITMO_HW/'
/content/gdrive/MyDrive/ITMO_HW

In [143]:
#считываем файл в датафрейм
df = pd.read_csv('train.csv')

In [144]:
#общая информация о датасете
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [146]:
#процент выживаемости в разрезе по классу
df.groupby('Pclass')['Survived'].mean().apply(lambda x: x * 100)

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [147]:
#самое популярное женское и мужское имя
#ТЗ не до конца понятно, имя - это значение Name целиком, или только то, что до зпт (или ещё что-то)?
#Первый вариант бессмысленный, т.к. все значения уникальные, поэтому беру только значение до зпт

#создазим копию df, в которой обрежем имя до зпт
df_nameShort = df
df_nameShort['Name'] = df_nameShort['Name'].str.split(",").str[0]

#решение
df_nameShort.groupby('Sex')['Name'].agg(lambda x: x.mode()[0])

Sex
female    Andersson
male         Panula
Name: Name, dtype: object

In [148]:
#Аналогично предыдущему блоку, но с разрезом до класса
df_nameShort.groupby(['Sex', 'Pclass'])['Name'].agg(lambda x: x.mode()[0])

Sex     Pclass
female  1           Allison
        2             Brown
        3         Andersson
male    1            Carter
        2           Hickman
        3            Panula
Name: Name, dtype: object

In [149]:
#часть таблицы с пассажирами, возраст которых больше 44 лет
df[df['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,McCarthy,male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,Bonnell,female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,Hewlett,female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,Wheadon,male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,Harper,female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,Daly,male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,Swift,female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,Beckwith,female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,Vander Cruyssen,male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,Potter,female,56.0,0,1,11767,83.1583,C50,C

In [150]:
#часть таблицы с пассажирами, возраст которых меньше 44 лет, и которые мужского пола
df[(df['Age'] > 44) & (df['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,McCarthy,male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,Wheadon,male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,Ostby,male,65.0,0,1,113509,61.9792,B30,C
62,63,0,1,Harris,male,45.0,1,0,36973,83.4750,C83,S
92,93,0,1,Chaffee,male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
...,...,...,...,...,...,...,...,...,...,...,...,...
771,772,0,3,Jensen,male,48.0,0,0,350047,7.8542,NaN,S
789,790,0,1,Guggenheim,male,46.0,0,0,PC 17593,79.2000,B82 B84,C
851,852,0,3,Svensson,male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,Daly,male,51.0,0,0,113055,26.5500,E17,S
873,874,0,3,Vander Cruyssen,male,47.0,0,0,345765,9.0000,NaN,S

In [151]:
#количества n-местных кабин (в которых было 2, 3, 4, ... человека)
#если правильно понял задание, то 1-местные кабины исключаем
#создадим Series, индексом которого будет кол-во мест, и выведем индекс > 1
s = df.groupby('Cabin')['Cabin'].count().value_counts()
s[s.index > 1]

Cabin
2    38
3     5
4     3
Name: count, dtype: int64